# Generated by Django 2.2 on 2019-04-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood', models.CharField(choices=[('O', 'Oak'), ('B', 'Beech'), ('P', 'Pine')], max_length=1)),
                ('size', models.CharField(choices=[('A', 'Adult'), ('C', 'Chd')], max_length=1)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Died',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Man')], max_length=1)),
                ('date_birthday', models.DateField()),
                ('date_died', models.DateField()),
                ('transcription', models.CharField(max_length=50)),
                ('outfit', models.CharField(max_length=200)),
                ('makeup', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('telephone_num', models.DecimalField(decimal_places=0, max_digits=9)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, 'One star'), (2, 'Two stars'), (3, 'Three stars'), (4, 'Four stars'), (5, 'Five stars')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('costs', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coffin', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.Coffin')),
                ('died', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.Died')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msc_type', models.CharField(choices=[('T', 'Trumpet'), ('O', 'Organ')], max_length=1)),
                ('telephone_num', models.DecimalField(decimal_places=0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('B', 'Big')], max_length=1)),
                ('color', models.CharField(choices=[('Wh', 'White flowers'), ('Bl', 'Blue flowers'), ('Pi', 'Pink flowers'), ('Ot', 'Other color flowers')], max_length=2)),
                ('count', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Order')),
            ],
        ),
    ]
