# Generated by Django 2.2 on 2019-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_num',
            field=models.IntegerField(),
        ),
    ]
