# Generated by Django 2.2 on 2019-04-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190427_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='order',
        ),
        migrations.RemoveField(
            model_name='music',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='flowers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Flowers'),
        ),
        migrations.AddField(
            model_name='order',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Music'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coffin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Coffin'),
        ),
        migrations.AlterField(
            model_name='order',
            name='died',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Died'),
        ),
    ]
