# Generated by Django 2.2 on 2019-05-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190428_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowers',
            name='price',
        ),
        migrations.RemoveField(
            model_name='music',
            name='price',
        ),
    ]
