# Generated by Django 2.2 on 2019-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190505_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='telephone_num',
        ),
        migrations.AddField(
            model_name='music',
            name='songs',
            field=models.TextField(default=8),
            preserve_default=False,
        ),
    ]
