# Generated by Django 2.2 on 2019-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190514_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
