# Generated by Django 2.2 on 2019-05-15 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190515_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
