# Generated by Django 2.2 on 2019-05-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190519_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='price_M',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
