# Generated by Django 2.2 on 2019-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190519_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='price_M',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
