# Generated by Django 2.2 on 2019-05-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190519_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='price_M',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
