# Generated by Django 2.2 on 2019-05-19 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190519_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='price_M',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
