# Generated by Django 2.2 on 2019-05-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190519_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='died',
            name='price_D',
        ),
    ]
