# Generated by Django 2.2 on 2019-06-03 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190603_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='died',
        ),
        migrations.AddField(
            model_name='died',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
    ]
