# Generated by Django 2.2 on 2019-06-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190603_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='died',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='died',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Died'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coffin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Coffin'),
        ),
    ]
